language: python

python:
  - 3.6

bundler_args: --retry 3

install:
  - sudo apt-get update
  - sudo apt-get install gfortran
  - sudo apt-get install texlive texlive-science texlive-latex-extra texlive-bibtex-extra texlive-fonts-extra
  - sudo apt-get install r-base
  - sudo su - -c "R -e \"install.packages('icc', repos='https://cran.r-project.org/src/contrib/ICC_2.3.0.tar.gz')\""
  - ./utils/travis_miniconda.sh
  - PATH="$HOME/miniconda/bin:$PATH"
  - conda env create -f environment.yml

script:
  - source .envrc
  - travis_wait run-notebook
  - travis_wait run-slide
