name: teaching-microeconometrics

channels:
- conda
- conda-forge
- r

dependencies:
- numpy
- libgfortran 
- pandas
- pandas-datareader
- flake8
- pytest
- scipy
- jupyterlab
- matplotlib
- seaborn
- jupyter
- jupyter_contrib_nbextensions
- jupyter_nbextensions_configurator
- pip
- pygraphviz
- rise
- r-essentials
- rpy2
- simplegeneric
- pip:
        - linearmodels
